# Generated by Django 4.2.11 on 2024-03-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickModel',
            fields=[
                ('count_id', models.AutoField(primary_key=True, serialize=False)),
                ('clicked_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
