# Generated by Django 4.2.11 on 2024-05-30 08:31

"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_clicks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickmodel',
            name='clicked_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
"""
# 기존 데이터를 유지하기 위해, 새로운 필드를 추가하고, 데이터를 변환한 후, 원래 필드를 제

from django.db import migrations, models
import django.utils.timezone
from datetime import datetime, time

def forwards_func(apps, schema_editor):
    ClickModel = apps.get_model('count_clicks', 'ClickModel')
    for click in ClickModel.objects.all():
        click.clicked_date = django.utils.timezone.make_aware(
            datetime.combine(click.clicked_date, datetime.min.time())
        )
        click.save()

class Migration(migrations.Migration):

    dependencies = [
        ('count_clicks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickmodel',
            name='clicked_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RunPython(forwards_func),
    ]
